<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Data
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */

// Call Xyster_Data_ClauseTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Data_ClauseTest::main');
}

require_once dirname(dirname(dirname(__FILE__))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'PHPUnit/Framework.php';
require_once 'Xyster/Data/Clause.php';

/**
 * Test class for Xyster_Data_Clause.
 * Generated by PHPUnit on 2008-02-08 at 12:15:44.
 */
abstract class Xyster_Data_ClauseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Xyster_Data_Clause
     */
    protected $object;
    
    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
    	$type = $this->_getType();
    	$this->object = $type->getClass()->newInstance();
    	foreach( $this->_getItems() as $item ) {
    		$this->object->add($item);
    	}
    }
    
    /**
     * Tests the 'add' method
     */
    public function testAdd()
    {
    	$items = $this->_getItems();
    	$count = count($this->object);
    	$return = $this->object->add($items[0]);
    	$this->assertSame($this->object, $return);
    	$this->assertGreaterThan($count, count($this->object));
    }

    /**
     * Tests the 'add' method with the wrong type
     *
     */
    public function testAddWrongType()
    {
    	$this->setExpectedException('Xyster_Data_Clause_Exception');
    	$this->object->add(new Xyster_Data_ClauseTest_Symbol);
    }
    
    /**
     * Tests the 'count' method
     */
    public function testCount()
    {
        $this->assertEquals(count($this->_getItems()), count($this->object));
    }

    /**
     * Tests the 'getIterator' method
     */
    public function testGetIterator()
    {
        $this->assertType('ArrayIterator', $this->object->getIterator());
        $this->assertType('EmptyIterator', $this->_makeNew()->getIterator());        
    }

    /**
     * Tests the 'merge' method
     */
    public function testMerge()
    {
    	$count = count($this->object);
        $return = $this->object->merge($this->object);
        $this->assertSame($this->object, $return);
        $this->assertEquals($count*2, count($this->object));
    }

    /**
     * Tests trying to add the wrong type
     *
     */
    public function testMergeWrongType()
    {
    	$this->setExpectedException('Xyster_Data_Clause_Exception');
    	$this->object->merge(new Xyster_Data_ClauseTest_SymbolClause);
    }
    
    /**
     * Tests the 'remove' method
     */
    public function testRemove()
    {
        $count = count($this->object);
        $return = $this->object->remove(current($this->_getItems()));
        $this->assertTrue($return);
        $this->assertLessThan($count, count($this->object));
    }

    /**
     * Tests the 'remove' method
     */
    public function testRemoveNotThere()
    {
    	$return = $this->object->remove(new Xyster_Data_ClauseTest_Symbol);
    	$this->assertFalse($return);
    }
    
    /**
     * Tests the 'toArray' method
     */
    public function testToArray()
    {
        $this->assertEquals($this->_getItems(), $this->object->toArray());
    }

    /**
     * Tests the 'toString' method
     */
    public function test__toString()
    {
        $this->assertEquals(implode(', ', $this->_getItems()), $this->object->__toString());
    }
    
    /**
     * Gets the items to be added to the clause
     *
     * @return array
     */
    abstract protected function _getItems();
    
    /**
     * Gets the type of the clause to be tested
     *
     * @return Xyster_Type
     */
    abstract protected function _getType();
    
    /**
     * Uses reflection to create a new instance of the clause
     *
     * @return Xyster_Data_Clause
     */
    protected function _makeNew()
    {
    	$type = Xyster_Type::of($this->object);
    	return $type->getClass()->newInstance();
    }
}

class Xyster_Data_ClauseTest_Symbol implements Xyster_Data_Symbol
{
	public function __toString()
	{
		return 'testing';
	}
}

class Xyster_Data_ClauseTest_SymbolClause extends Xyster_Data_Clause
{
    static private $_type;
    
    public function __construct()
    {
        if ( !self::$_type instanceof Xyster_Type ) {
            self::$_type = new Xyster_Type('Xyster_Data_ClauseTest_Symbol');
        }
        parent::__construct(self::$_type);
    }
}

// Call Xyster_Data_ClauseTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Data_ClauseTest::main') {
    Xyster_Data_ClauseTest::main();
}
