<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   Xyster_Application
 * @subpackage   UnitTests
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_ContainerTest::main');
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR . 'TestHelper.php';

require_once 'Xyster/Container.php';

/**
 * Test class for Xyster_Container.
 * Generated by PHPUnit on 2007-12-12 at 19:40:53.
 */
class Xyster_ContainerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Xyster_Container
     */
    protected $object;

    /**
     * Runs the test methods of this class.
     *
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite(__CLASS__);
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture
     *
     */
    protected function setUp()
    {
        $this->object = new Xyster_Container;
    }

    /**
     * Tests the 'accept' method
     */
    public function testAccept()
    {
        $this->object->addComponentInstance(new ArrayObject);
        require_once 'Xyster/Container/Visitor/Mock.php';
        $visitor = new Xyster_Container_Visitor_Mock;
        $this->object->accept($visitor);
        $this->assertEquals(1, $visitor->getCalled('visitContainer'));
        $this->assertEquals(1, $visitor->getCalled('visitComponentAdapter'));
    }

    /**
     * Tests the 'addAdapter' method
     */
    public function testAddAdapter()
    {
        require_once 'Xyster/Container/Adapter/Instance.php';
        $key = new Xyster_Type('ArrayObject');
        $adapter = new Xyster_Container_Adapter_Instance($key, new ArrayObject);
        $return = $this->object->addAdapter($adapter);
        $this->assertSame($this->object, $return);
        $adapter2 = $this->object->getComponentAdapter($key);
        $this->assertSame($adapter, $adapter2);
    }

    /**
     * Tests the 'addComponent' method
     */
    public function testAddComponent()
    {
        $class = new Xyster_Type('Xyster_Collection_Map');
        $return = $this->object->addComponent($class);
        $this->assertSame($this->object, $return);
        $adapter = $this->object->getComponentAdapterByType($class);
        $this->assertType('Xyster_Container_Adapter', $adapter);
        $this->assertSame($class, $adapter->getKey());
    }
    
    /**
     * Tests the 'addComponent' method with an instance of an object
     *
     */
    public function testAddComponentInstance()
    {
        $instance = new ArrayObject;
        $return = $this->object->addComponentInstance($instance);
        $this->assertSame($this->object, $return);
        $key = new Xyster_Type('ArrayObject');
        $adapter = $this->object->getComponentAdapterByType($key);
        $this->assertType('Xyster_Container_Adapter_Instance', $adapter);
        $this->assertSame($instance, $adapter->getInstance($this->object));
        $this->assertEquals($key, $adapter->getImplementation());
    }

    /**
     * @todo Implement testChange().
     */
    public function testChange()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * Tests the 'changeMonitor' method
     */
    public function testChangeMonitor()
    {
        require_once 'Xyster/Container/Monitor/Null.php';
        $monitor = new Xyster_Container_Monitor_Null;
        $this->object->changeMonitor($monitor);
        $this->assertAttributeSame($monitor, '_monitor', $this->object);
    }

    /**
     * Tests the 'currentMonitor' method
     */
    public function testCurrentMonitor()
    {
        $this->assertAttributeSame($this->object->currentMonitor(), '_monitor', $this->object);
    }

    /**
     * @todo Implement testGetComponent().
     */
    public function testGetComponent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetComponents().
     */
    public function testGetComponents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetComponentAdapter().
     */
    public function testGetComponentAdapter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetComponentAdapterByType().
     */
    public function testGetComponentAdapterByType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetComponentAdapters().
     */
    public function testGetComponentAdapters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRemoveComponent().
     */
    public function testRemoveComponent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRemoveComponentByInstance().
     */
    public function testRemoveComponentByInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testWith().
     */
    public function testWith()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}

// Call Xyster_ContainerTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_ContainerTest::main') {
    Xyster_ContainerTest::main();
}
