<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Db
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
// Call Xyster_Db_Gateway_AbstractTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Db_Gateway_AbstractTest::main');
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";
require_once dirname(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'Xyster/Db/Gateway/Abstract.php';
require_once 'Xyster/Db/Gateway/Stub.php';
require_once 'Zend/Db/Adapter/Pdo/Sqlite.php';

/**
 * Test class for Xyster_Db_Gateway_Abstract.
 * Generated by PHPUnit on 2008-03-12 at 19:41:18.
 */
class Xyster_Db_Gateway_AbstractTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Xyster_Db_Gateway_Abstract
     */
    protected $object;
    
    /**
     * @var Zend_Db_Adapter_Abstract
     */
    protected $db;

    /**
     * Runs the test methods of this class.
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Db_Gateway_AbstractTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture
     *
     */
    protected function setUp()
    {
    	$this->db = new Zend_Db_Adapter_Pdo_Sqlite(array('host'=>':memory:', 'dbname'=>''));
        $this->object = new Xyster_Db_Gateway_Stub;
    }
    
    /**
     * Tests the getting and setting of an adapter
     *
     */
    public function testGetAndSetAdapter()
    {
    	$this->assertNull($this->object->getAdapter());
    	$return = $this->object->setAdapter($this->db);
    	$this->assertSame($this->db, $this->object->getAdapter());
    	$this->assertSame($this->object, $return);
    }
    
    /**
     * Tests if passing the adapter to the constructor will work
     *
     */
    public function testConstructor()
    {
    	$gateway = new Xyster_Db_Gateway_AbstractTest_Stub($this->db);
    	$this->assertSame($this->db, $gateway->getAdapter());
    }
}

// Call Xyster_Db_Gateway_AbstractTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Db_Gateway_AbstractTest::main') {
    Xyster_Db_Gateway_AbstractTest::main();
}
