<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Db
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
// Call Xyster_Db_Gateway_BuilderTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Db_Gateway_BuilderTest::main');
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";
require_once dirname(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'Xyster/Db/Gateway/Builder.php';
require_once 'Xyster/Db/Gateway/Stub.php';

/**
 * Test class for Xyster_Db_Gateway_Builder.
 * Generated by PHPUnit on 2008-04-21 at 20:32:04.
 */
class Xyster_Db_Gateway_BuilderTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Xyster_Db_Gateway_Builder
     */
    protected $object;
    
    protected $gateway;
    
    protected $name = 'foobar';
    
    protected $schema = 'nothing';

    /**
     * Runs the test methods of this class.
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Db_Gateway_BuilderTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->gateway = new Xyster_Db_Gateway_Stub;
        $this->object = new Xyster_Db_Gateway_BuilderStub($this->gateway, $this->name, $this->schema);
    }

    /**
     * Tests the 'getName' method
     */
    public function testGetName()
    {
        $this->assertEquals($this->name, $this->object->getName());
    }
    
    /**
     * Tests the 'getSchema' method
     */
    public function testGetSchema()
    {
        $this->assertEquals($this->schema, $this->object->getSchema());
    }
    
    /**
     * Tests the '_getGateway' method
     *
     */
    public function testGetGateway()
    {
        $this->assertSame($this->gateway, $this->object->getGateway());
    }
}

class Xyster_Db_Gateway_BuilderStub extends Xyster_Db_Gateway_Builder
{
    public function getGateway()
    {
        return $this->_getGateway();
    }
    public function execute()
    {
    }
}

// Call Xyster_Db_Gateway_BuilderTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Db_Gateway_BuilderTest::main') {
    Xyster_Db_Gateway_BuilderTest::main();
}
