<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Db
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";
require_once dirname(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'Zend/Db.php';

/**
 * Test class for Xyster_Db_Gateway_TableBuilder.
 * Generated by PHPUnit on 2008-03-17 at 19:04:52.
 */
abstract class Xyster_Db_Gateway_TestCommon extends PHPUnit_Framework_TestCase
{
    /**
     * @var Zend_Db_Adapter_Abstract
     */
    protected $_db;
    
    /**
     * @var Xyster_Db_Gateway_Abstract
     */
    protected $object;
    
    /**
     * Sets up the test
     *
     */
    protected function setUp()
    {
        $this->_db = Zend_Db::factory($this->getDriver(), $this->getConfig());
        $className = 'Xyster_Db_Gateway_' . $this->getDriver(); 
        try {
            $conn = $this->_db->getConnection();
            $this->object = new $className($this->_db);
        } catch (Zend_Exception $e) {
            $this->_db = null;
            $this->assertType('Zend_Db_Adapter_Exception', $e,
                'Expecting Zend_Db_Adapter_Exception, got ' . get_class($e));
            echo $e->getMessage() . "\n";
            $this->markTestSkipped($e->getMessage());
        }
    }
    
    /**
     * Cleans up any tables created
     *
     */
    protected function tearDown()
    {
        $tables = $this->_db->listTables();
        $drop = array('forum', 'message_board', 'forum_user');
        foreach( $tables as $name ) {
            if ( in_array($name, $drop) ) {
                $this->_db->query('DROP TABLE ' . $name);
            }
        }
        $indexes = $this->object->listIndexes();
        foreach( $indexes as $name => $values ) {
            if ( in_array($name, array('my_example_index')) ) {
                $this->object->dropIndex($name, $values['TABLE_NAME']);
            }
        }
        if ( $this->object->supportsSequences() ) {
            $sequences = $this->object->listSequences();
            foreach( $sequences as $name ) {
                if ( in_array($name, array('my_sequence', 'my_sequence_awesome')) ) {
                    $this->_db->query('DROP SEQUENCE ' . $name);
                }
            }
        }
    }
    
    /**
     * Gets the configuration for the database adapter
     * 
     * @return array
     */
    abstract public function getConfig();
        
    /**
     * Gets the type of adapter
     *
     * @return string
     */
    abstract public function getDriver();
    
    /**
     * Gets the options for the TableBuilder
     *
     * @return array
     */
    public function getOptions()
    {
        return array();
    }
    
    /**
     * Tests the 'addColumn' method
     */
    public function testAddColumn()
    {
        $this->_setupTestTable();
        $describe = $this->_db->describeTable('forum');
        $this->assertArrayNotHasKey('category_id', $describe);
        $this->object->addColumn('forum', 'category_id',
            Xyster_Db_DataType::Integer());
        
        $describe2 = $this->_db->describeTable('forum');
        $this->assertArrayHasKey('category_id', $describe2);
        $this->assertEquals('category_id', $describe2['category_id']['COLUMN_NAME']);
        $this->assertEquals('int', strtolower(substr($describe2['category_id']['DATA_TYPE'], 0, 3)));
    }
    
    /**
     * Adds a primary key to a table
     */
    public function testAddPrimaryOneColumn()
    {
        $builder = $this->object->createTable('forum');
        $builder->addInteger('forum_id')->null(false)
            ->addVarchar('username', 50)
            ->addVarchar('title', 255)
            ->addClob('message')
            ->addTimestamp('created_on')
            ->execute();
        $describe = $this->_db->describeTable('forum');
        $this->assertFalse($describe['forum_id']['PRIMARY']);
        $this->object->addPrimary('forum', 'forum_id');
        $describe2 = $this->_db->describeTable('forum');
        $this->assertTrue($describe2['forum_id']['PRIMARY']);
    }
    
    /**
     * Adds a primary key to a table
     */
    public function testAddPrimaryMultiColumn()
    {
        $builder = $this->object->createTable('forum');
        $builder->addInteger('forum_id')->null(false)
            ->addVarchar('username', 50)->null(false)
            ->addVarchar('title', 255)
            ->addClob('message')
            ->addTimestamp('created_on')
            ->execute();
        $describe = $this->_db->describeTable('forum');
        $this->assertFalse($describe['forum_id']['PRIMARY']);
        $this->assertFalse($describe['username']['PRIMARY']);
        $this->object->addPrimary('forum', array('forum_id', 'username'));
        $describe2 = $this->_db->describeTable('forum');
        $this->assertTrue($describe2['forum_id']['PRIMARY']);
        $this->assertTrue($describe2['username']['PRIMARY']);
        $this->assertEquals(1, $describe2['forum_id']['PRIMARY_POSITION']);
        $this->assertEquals(2, $describe2['username']['PRIMARY_POSITION']);
    }
    
    
    /**
     * Creates a sequence
     */
    public function testCreateSequence()
    {
        if ( !$this->object->supportsSequences() ) {
            $this->markTestSkipped();
        }
        $name = 'my_sequence';
        $sequences = $this->object->listSequences();
        $this->assertNotContains($name, $sequences);
        $this->object->createSequence($name);
        $sequences2 = $this->object->listSequences();
        $this->assertContains($name, $sequences2);
    }
    
    /**
     * Creates a table builder
     */
    public function testCreateTable()
    {
        $builder = $this->object->createTable('mytable');
        $this->assertType('Xyster_Db_Gateway_TableBuilder', $builder);
        $this->assertEquals('mytable', $builder->getName());
    }
    
    /**
     * Removes a column from a table
     */
    public function testDropColumn()
    {
        $this->_setupTestTable();
        $describe = $this->_db->describeTable('forum');
        $this->assertArrayHasKey('username', $describe);
        
        $this->object->dropColumn('forum', 'username');
        
        $describe2 = $this->_db->describeTable('forum');
        $this->assertNotEquals($describe, $describe2);
        $this->assertArrayNotHasKey('username', $describe2);
    }
    
    /**
     * Drops a foreign key from a table
     * 
     */
    public function testDropForeign()
    {
        if ( !$this->object->supportsForeignKeys() ) {
            $this->markTestSkipped();
        }
        $this->_setupTestTable();
        $builder = $this->object->createTable('forum_user');
        foreach( $this->getOptions() as $name => $value ) {
            $builder->option($name, $value);
        }
        $builder->addVarchar('forum_username', 50)->primary()->null(false)
            ->addChar('gender', 1)
            ->addTimestamp('created_on')
            ->execute();
        $this->object->addForeign('forum', 'username', 'forum_user', 'forum_username');
        $keys = $this->object->listForeignKeys();
        $expected = array(
            'TABLE_NAME' => 'forum',
            'COLUMNS' => array('username'),
            'REFERENCED_TABLE_NAME' => 'forum_user',
            'REFERENCED_COLUMNS' => array('forum_username'),
            );
        $keyName = null;
        foreach( $keys as $name => $info ) {
            unset($info['SCHEMA_NAME']);
            unset($info['ON_DELETE']);
            unset($info['ON_UPDATE']);
            $expected['KEY_NAME'] = $info['KEY_NAME'];
            if ( $info == $expected ) {
                $keyName = $info['KEY_NAME'];
                break;
            }
        }
        if ( $keyName === null ) {
            $this->fail('The foreign key created was not found: ' . $keyName);
        }
        $this->object->dropForeign('forum', $keyName);
        $keys2 = $this->object->listForeignKeys();
        $this->assertArrayNotHasKey($keyName, $keys2);
    }
    
    /**
     * Removes an index
     */
    public function testDropIndex()
    {
        $this->_setupTestTable();
        $this->object->createIndex('my_example_index')->on('forum', array('username'))->execute();
        $indexes = $this->object->listIndexes();
        $this->assertArrayHasKey('my_example_index', $indexes);
        $this->object->dropIndex('my_example_index', 'forum');
        $indexes2 = $this->object->listIndexes();
        $this->assertArrayNotHasKey('my_example_index', $indexes2);
    }
    
    /**
     * Removes a primary key from a table
     */
    public function testDropPrimary()
    {
        $this->_setupTestTable();
        $describe = $this->_db->describeTable('forum');
        $this->assertTrue($describe['forum_id']['PRIMARY']);
        $this->assertEquals(1, $describe['forum_id']['PRIMARY_POSITION']);
        $this->object->dropPrimary('forum');
        $describe2 = $this->_db->describeTable('forum');
        $this->assertFalse($describe2['forum_id']['PRIMARY']);
        $this->assertEquals(null, $describe2['forum_id']['PRIMARY_POSITION']);
    }
    
    /**
     * Drops a sequence
     */
    public function testDropSequence()
    {
        if ( !$this->object->supportsSequences() ) {
            $this->markTestSkipped();
        }
        $name = 'my_sequence';
        $sequences = $this->object->listSequences();
        $this->assertNotContains($name, $sequences);
        $this->object->createSequence($name);
        $sequences2 = $this->object->listSequences();
        $this->assertContains($name, $sequences2);
        $this->object->dropSequence($name);
        $sequences3 = $this->object->listSequences();
        $this->assertNotContains($name, $sequences3);
    }
    
    /**
     * Tests the 'dropTable' method
     */
    public function testDropTable()
    {
        $this->_setupTestTable();
        $tables = $this->_db->listTables();
        $this->assertContains('forum', $tables);
        $this->object->dropTable('forum');
        $tables2 = $this->_db->listTables();
        $this->assertNotContains('forum', $tables2);
    }

    /**
     * Creates an index
     */
    public function testExecuteIndexBuilderOne()
    {
        $this->_setupTestTable();
        $indexes = $this->object->listIndexes();
        $this->assertArrayNotHasKey('my_example_index', $indexes);
        $this->object->createIndex('my_example_index')->on('forum', array('username'))->unique()->execute();
        $indexes2 = $this->object->listIndexes();
        $this->assertArrayHasKey('my_example_index', $indexes2);
        $this->assertEquals(array('username'), $indexes2['my_example_index']['COLUMNS']);
        $this->assertTrue($indexes2['my_example_index']['UNIQUE']);
    }
    
    /**
     * Creates an index
     */
    public function testExecuteIndexBuilderMulti()
    {
        $this->_setupTestTable();
        $indexes = $this->object->listIndexes();
        $this->assertArrayNotHasKey('my_example_index', $indexes);
        $this->object->createIndex('my_example_index')->on('forum', array('username', 'title'))->unique()->execute();
        $indexes2 = $this->object->listIndexes();
        $this->assertArrayHasKey('my_example_index', $indexes2);
        $this->assertEquals(array('username', 'title'), $indexes2['my_example_index']['COLUMNS']);
        $this->assertTrue($indexes2['my_example_index']['UNIQUE']);
    }
    
    /**
     * Tests the 'listForeignKeys' method
     *
     * This also tests the 'addForeign' method 
     */
    public function testListForeignKeys()
    {
        if ( !$this->object->supportsForeignKeys() ) {
            $this->markTestSkipped();
        }
        $this->_setupTestTable();
        $builder = $this->object->createTable('forum_user');
        foreach( $this->getOptions() as $name => $value ) {
            $builder->option($name, $value);
        }
        $builder->addVarchar('forum_username', 50)->primary()->null(false)
            ->addChar('gender', 1)
            ->addTimestamp('created_on')
            ->execute();
        $this->object->addForeign('forum', 'username', 'forum_user', 'forum_username');
        $keys = $this->object->listForeignKeys();
        $this->assertType('array', $keys);
        $expected = array(
            'TABLE_NAME' => 'forum',
            'COLUMNS' => array('username'),
            'REFERENCED_TABLE_NAME' => 'forum_user',
            'REFERENCED_COLUMNS' => array('forum_username'),
            );
        foreach( $keys as $name => $info ) {
            unset($info['SCHEMA_NAME']);
            unset($info['KEY_NAME']);
            unset($info['ON_DELETE']);
            unset($info['ON_UPDATE']);
            if ( $info == $expected ) {
                return;
            }
        }
        $this->fail('The foreign key created was not found in the list');
    }
    
    /**
     * Lists all indexes
     */
    public function testListIndexes()
    {
        $this->_setupTestTable();
        $this->object->createIndex('my_example_index')->on('forum', array('username', 'title'))->execute();
        $indexes = $this->object->listIndexes();
        $this->assertType('array', $indexes);
        $this->assertArrayHasKey('my_example_index', $indexes);
        $index = array(
                'INDEX_NAME' => 'my_example_index',
                'TABLE_NAME' => 'forum',
                'COLUMNS' => array('username', 'title'),
                'PRIMARY' => false,
                'UNIQUE' => false
            );
        $realIndex = $indexes['my_example_index'];
        unset($realIndex['SCHEMA_NAME']);
        $this->assertEquals($index, $realIndex);
    }
    
    /**
     * Lists all sequences
     */
    public function testListSequences()
    {
        if ( !$this->object->supportsSequences() ) {
            $this->markTestSkipped();
        }
        $return = $this->object->listSequences();
        $this->assertType('array', $return);
    }
    
    /**
     * Renames a column
     */
    public function testRenameColumn()
    {
        $this->_setupTestTable();
        $describe = $this->_db->describeTable('forum');
        $this->assertArrayHasKey('title', $describe);
        $this->object->renameColumn('forum', 'title', 'subject');
        $describe2 = $this->_db->describeTable('forum');
        $this->assertArrayHasKey('subject', $describe2);
        $this->assertArrayNotHasKey('title', $describe2);
        foreach( $describe2['subject'] as $key => $value ) {
            if ( $key != 'COLUMN_NAME' ) {
                $this->assertEquals($describe['title'][$key], $value, $key . ' is not the same as the original');
            }
        }
    }
    
    /**
     * Renames an index
     * 
     */
    public function testRenameIndex()
    {
        $indexName = 'my_example_index';
        $table = 'forum';
        $columns = array('username'); 
        $this->_setupTestTable();
        $indexes = $this->object->listIndexes();
        $this->assertArrayNotHasKey($indexName, $indexes);
        $this->object->createIndex($indexName)->on($table, $columns)->execute();
        $indexes2 = $this->object->listIndexes();
        $this->assertArrayHasKey($indexName, $indexes2);
        $this->assertEquals($columns, $indexes2[$indexName]['COLUMNS']);
        $this->object->renameIndex($indexName, 'my_renamed_example_index', $table);
        $indexes3 = $this->object->listIndexes();
        $this->assertArrayHasKey('my_renamed_example_index', $indexes3);
        $this->assertArrayNotHasKey($indexName, $indexes3);
        $this->assertEquals($columns, $indexes3['my_renamed_example_index']['COLUMNS']);
    }
    
    /**
     * Renames a sequence
     */
    public function testRenameSequence()
    {
        if ( !$this->object->supportsSequences() ) {
            $this->markTestSkipped();
        }
        $name = 'my_sequence';
        $sequences = $this->object->listSequences();
        $this->assertNotContains($name, $sequences);
        $this->object->createSequence($name);
        $sequences2 = $this->object->listSequences();
        $this->assertContains($name, $sequences2);
        $this->object->renameSequence($name, $name.'_awesome');
        $sequences3 = $this->object->listSequences();
        $this->assertContains($name.'_awesome', $sequences3);
    }
    
    /**
     * Renames a table
     */
    public function testRenameTable()
    {
        $this->_setupTestTable();
        $tables = $this->_db->listTables();
        $this->assertContains('forum', $tables);
        $this->object->renameTable('forum', 'message_board');
        $tables2 = $this->_db->listTables();
        $this->assertContains('message_board', $tables2);
        $this->assertNotContains('forum', $tables2);
    }
    
    /**
     * Sets the default value for a column
     */
    public function testSetDefault()
    {
        $this->_setupTestTable();
        $describe = $this->_db->describeTable('forum');
        $this->assertEquals('', $describe['title']['DEFAULT']);
        $this->object->setDefault('forum', 'title', 'Default title of post');
        $describe2 = $this->_db->describeTable('forum');
        $this->assertEquals('Default title of post', $describe2['title']['DEFAULT']);
        foreach( $describe2['title'] as $key => $value ) {
            if ( $key != 'DEFAULT' ) {
                $this->assertEquals($describe['title'][$key], $value, $key . ' is not the same as the original');
            }
        }
    }
    
    /**
     * Sets whether or not the column will accept null
     */
    public function testSetNull()
    {
        $this->_setupTestTable();
        $describe = $this->_db->describeTable('forum');
        $this->assertFalse($describe['title']['NULLABLE']);
        $this->object->setNull('forum', 'title', true);
        $describe2 = $this->_db->describeTable('forum');
        $this->assertTrue($describe2['title']['NULLABLE']);
        foreach( $describe2['title'] as $key => $value ) {
            if ( $key != 'NULLABLE' ) {
                $this->assertEquals($describe['title'][$key], $value, $key . ' is not the same as the original');
            }
        }
    }
    
    /**
     * Creates a unique index on a column or columns
     * 
     */
    public function testSetUnique()
    {
        $indexes = $this->object->listIndexes();
        $found = false;
        foreach( $indexes as $name => $info ) {
            if ( $info['TABLE_NAME'] == 'forum' && $info['COLUMNS'] == array('title') ) {
                $found = true;
                break;
            }
        }
        if ( $found ) {
            $this->fail('The unique index was already defined');
        }
        $this->_setupTestTable();
        $this->object->setUnique('forum', 'title');
        $indexes2 = $this->object->listIndexes();
        $found = false;
        foreach( $indexes2 as $name => $info ) {
            if ( $info['TABLE_NAME'] == 'forum' && $info['COLUMNS'] == array('title') ) {
                $found = true;
                break;
            }
        }
        if ( !$found ) {
            $this->fail('The unique index was not found');
        }
    }
    
    /**
     * Changes the type of a column
     */
    public function testSetType()
    {
        $this->_setupTestTable();
        $describe = $this->_db->describeTable('forum');
        $this->assertNotEquals('varchar', $describe['message']['DATA_TYPE']);
        $this->object->setType('forum', 'title', Xyster_Db_DataType::Varchar(), 255);
        $describe2 = $this->_db->describeTable('forum');
        $this->assertEquals('varchar', $describe2['title']['DATA_TYPE']);
        $this->assertEquals(255, $describe2['title']['LENGTH']);
        foreach( $describe2['title'] as $key => $value ) {
            if ( $key != 'DATA_TYPE' && $key != 'LENGTH' ) {
                $this->assertEquals($describe['title'][$key], $value, $key . ' is not the same as the original');
            }
        }
    }
    
    /**
     * Sets up a single test table
     *
     */
    protected function _setupTestTable()
    {
        $builder = $this->object->createTable('forum');
        foreach( $this->getOptions() as $name => $value ) {
            $builder->option($name, $value);
        }
        $builder->addInteger('forum_id')->primary()->null(false)
            ->addVarchar('username', 50)
            ->addVarchar('title', 255)->null(false)
            ->addClob('message')
            ->addTimestamp('created_on')
            ->execute();
    }
}