<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Orm
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
// Call Xyster_Orm_Engine_ValueInclusionTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Orm_Engine_ValueInclusionTest::main');
}
require_once dirname(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'Xyster/Orm/Engine/ValueInclusion.php';

/**
 * Test class for Xyster_Orm_Engine_ValueInclusion.
 * Generated by PHPUnit on 2008-08-02 at 13:35:25.
 */
class Xyster_Orm_Engine_ValueInclusionTest extends PHPUnit_Framework_TestCase
{
    /**
     * Runs the test methods of this class.
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';
        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Orm_Engine_ValueInclusionTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Tests the 'none' method
     */
    public function testNone()
    {
        $enum = Xyster_Orm_Engine_ValueInclusion::None();
        $this->_runTests($enum, 'None', 0);
    }

    /**
     * Tests the 'partial' method
     */
    public function testPartial()
    {
        $enum = Xyster_Orm_Engine_ValueInclusion::Partial();
        $this->_runTests($enum, 'Partial', 1);
    }

    /**
     * Tests the 'full' method
     */
    public function testFull()
    {
        $enum = Xyster_Orm_Engine_ValueInclusion::Full();
        $this->_runTests($enum, 'Full', 2);
    }
    
    /**
     * Runs the unit tests on an enum
     *
     * @param Xyster_Enum $actual
     * @param string $name
     * @param mixed $value
     */
    protected function _runTests( Xyster_Orm_Engine_ValueInclusion $actual, $name, $value )
    {
        $this->assertEquals($name, $actual->getName());
        $this->assertEquals($value, $actual->getValue());
        $this->assertEquals('Xyster_Orm_Engine_ValueInclusion ['.$value.','.$name.']', (string)$actual);
        $this->assertSame($actual, Xyster_Enum::parse('Xyster_Orm_Engine_ValueInclusion', $name));
        $this->assertSame($actual, Xyster_Enum::valueOf('Xyster_Orm_Engine_ValueInclusion', $value));
    }
}

// Call Xyster_Orm_Engine_ValueInclusionTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Orm_Engine_ValueInclusionTest::main') {
    Xyster_Orm_Engine_ValueInclusionTest::main();
}
