<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Acl
 * @copyright Copyright LibreWorks, LLC (http://libreworks.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
namespace XysterTest\Acl\Role;
use Xyster\Acl\Role\Provider;
/**
 * Test class for Xyster_Acl_Role_Provider.
 * Generated by PHPUnit on 2007-09-11 at 19:28:58.
 */
class Xyster_Acl_Role_ProviderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Provider
     */
    public $provider;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     */
    protected function setUp()
    {
        $this->provider = new Provider();
    }
    
    /**
     * Tests the 'getRole' method
     *
     */
    public function testGetRole()
    {
        $role = $this->provider->getRole('myUsername');
        
        $this->assertType('\Zend_Acl_Role_Interface', $role);
        $this->assertEquals('myUsername', $role->getRoleId());
    }
    
    /**
     * Tests the 'getParents' method
     *
     */
    public function testGetParents()
    {
        $parents = $this->provider->getRoleParents(new \Zend_Acl_Role('myUsername'));
        
        $this->assertType('array', $parents);
        $this->assertEquals(0, count($parents));
    }
}
