<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Orm
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
// Call Xyster_Orm_Context_EntityUniqueKeyTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Orm_Context_EntityUniqueKeyTest::main');
}
require_once dirname(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'Xyster/Orm/Context/EntityUniqueKey.php';
require_once 'Xyster/Orm/Type/Integer.php';

/**
 * Test class for Xyster_Orm_Context_EntityUniqueKey.
 * Generated by PHPUnit on 2008-10-06 at 20:16:12.
 */
class Xyster_Orm_Context_EntityUniqueKeyTest extends PHPUnit_Framework_TestCase
{
    /**
     * Runs the test methods of this class.
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';
        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Orm_Context_EntityUniqueKeyTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Tests the 'equals' method
     */
    public function testEquals()
    {
        $type = new Xyster_Orm_Type_Integer;
        $key1 = new Xyster_Orm_Context_EntityUniqueKey('Foobar', 'uk', 123, $type);
        $key2 = new Xyster_Orm_Context_EntityUniqueKey('Foobar', 'uk', 123, $type);
        $key3 = new Xyster_Orm_Context_EntityUniqueKey('Barfoo', 'uk', 123, $type);
        $key4 = new Xyster_Orm_Context_EntityUniqueKey('Foobar', 'fb', 123, $type);
        $key5 = new Xyster_Orm_Context_EntityUniqueKey('Foobar', 'uk', 456, $type);
        
        $this->assertTrue($key1->equals($key1));
        $this->assertTrue($key1->equals($key2));
        $this->assertFalse($key1->equals($key3));
        $this->assertFalse($key1->equals($key4));
        $this->assertFalse($key1->equals($key5));
    }

    /**
     * Tests basic construction and usage
     */
    public function testConstruct()
    {
        $type = new Xyster_Orm_Type_Integer;
        $key = new Xyster_Orm_Context_EntityUniqueKey('Foobar', 'uk', 123, $type);
        $this->assertEquals('Foobar', $key->getEntityName());
        $this->assertEquals('uk', $key->getUniqueKeyName());
        $this->assertEquals(123, $key->getKey());
    }

    /**
     * Tests the 'hashCode' method
     */
    public function testHashCode()
    {
        $hash = Xyster_Type::hash(array('Foobar', 'uk', 123));
        
        $type = new Xyster_Orm_Type_Integer;
        $key = new Xyster_Orm_Context_EntityUniqueKey('Foobar', 'uk', 123, $type);
        $this->assertEquals($hash, $key->hashCode());
    }
}

// Call Xyster_Orm_Context_EntityUniqueKeyTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Orm_Context_EntityUniqueKeyTest::main') {
    Xyster_Orm_Context_EntityUniqueKeyTest::main();
}
