<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Orm
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
// Call Xyster_Orm_Plugin_AclTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Orm_Plugin_AclTest::main');
}

require_once 'PHPUnit/Framework.php';

require_once dirname(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR . 'TestHelper.php';

require_once 'Xyster/Orm/Plugin/_files/TestEntity.php';
require_once 'Xyster/Orm/Plugin/Acl.php';
require_once 'Zend/Acl.php';

/**
 * Test class for Xyster_Orm_Plugin_Acl.
 * Generated by PHPUnit on 2007-10-07 at 11:59:12.
 */
class Xyster_Orm_Plugin_AclTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Zend_Acl
     */
    public $acl;
    
    /**
     * The mock test plugin
     *
     * @var Xyster_Orm_Plugin_Acl
     */
    public $plugin;
    
    /**
     * Runs the test methods of this class.
     *
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite(__CLASS__);
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * This method is called before a test is executed.
     *
     */
    protected function setUp()
    {
        $this->acl = new Zend_Acl;
        $this->plugin = new Xyster_Orm_Plugin_Acl($this->acl);
    }

    /**
     * Tests the 'getAcl' method
     *
     */
    public function testGetAcl()
    {
        $this->assertSame($this->acl, $this->plugin->getAcl());
    }
    
    /**
     * Tests the 'postLoad' methodc
     */
    public function testPostLoad()
    {
        $entity = new Xyster_Orm_Plugin_TestEntity;
        $this->assertType('string', $entity->getResourceId());
        $this->assertFalse($this->acl->has($entity));
        $this->plugin->postLoad($entity);
        $this->assertTrue($this->acl->has($entity));
    }
}

// Call Xyster_Orm_Plugin_AclTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Orm_Plugin_AclTest::main') {
    Xyster_Orm_Plugin_AclTest::main();
}
