<?php
// Call Xyster_Validate_UriTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Validate_UriTest::main');
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once dirname(dirname(dirname(__FILE__))) . DIRECTORY_SEPARATOR . 'TestHelper.php';

require_once 'Xyster/Validate/Uri.php';

/**
 * Test class for Xyster_Validate_Uri.
 * Generated by PHPUnit on 2007-09-11 at 19:28:58.
 */
class Xyster_Validate_UriTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Xyster_Validate_Uri
     */
    public $validator;
    
    /**
     * Runs the test methods of this class.
     *
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Validate_UriTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     */
    protected function setUp()
    {
        $this->validator = new Xyster_Validate_Uri();
    }
    
    /**
     * Tests basic validation for a URI
     *
     */
    public function testBasic()
    {
        $valuesExpected = array(
            array('', false),
            array('://xyster.devweblog.org', false),
            array('!@#$%^&*()', false),
            array('unsupported', false),
            array('unsupported://devweblog.org', false),
            array('http://xyster.devweblog.org', true),
            array('https://testing.devweblog.org:443/someDirectory/ItsOkay%20ToHave/', true)
            );
        foreach ($valuesExpected as $element) {
            $this->assertEquals($element[1], $this->validator->isValid($element[0]));
        }
    }
    
    /**
     * Ensures that getMessages() returns expected default value
     *
     * @return void
     */
    public function testGetMessages()
    {
        $this->assertEquals(array(), $this->validator->getMessages());
    }
    
}

// Call Xyster_Validate_UriTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Validate_UriTest::main') {
    Xyster_Validate_UriTest::main();
}
