<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Container
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */

// Call Xyster_Container_Behavior_PropertyApplicatorTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Container_Behavior_PropertyApplicatorTest::main');
}

require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'CommonTest.php';

require_once 'PHPUnit/Framework.php';
require_once 'Xyster/Container/Behavior/PropertyApplicator.php';
require_once dirname(dirname(__FILE__)) . '/_files/Cdi.php';

/**
 * Test class for Xyster_Container_Behavior_PropertyApplicator.
 * Generated by PHPUnit on 2008-01-06 at 13:12:01.
 */
class Xyster_Container_Behavior_PropertyApplicatorTest extends Xyster_Container_Behavior_CommonTest
{
    /**
     * @var Xyster_Container_Behavior_PropertyApplicator
     */
    protected $object;

    /**
     * Runs the test methods of this class.
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Container_Behavior_PropertyApplicatorTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $key = new Xyster_Type('Submarine');
        $this->container = new Xyster_Container;
        $this->container->addComponent($key)
            ->addConfig('name', 'Captain Crunch')
            ->addComponent('ScubaGear')
            ->addComponent('SubmarineCaptain')
            ->addComponent('SubFuel')
            ->addComponent('array');
        $this->delegate = $this->container->getComponentAdapter($key);
        $this->object = new Xyster_Container_Behavior_PropertyApplicator($this->delegate);
    }

    /**
     * Tests the 'getInstance' method
     */
    public function testGetInstance()
    {
        $this->object->setProperty('name', 'U.S.S. Submergible');
        $this->object->setProperty('foo', 'bar');
        $this->object->setProperty('location', null);
        $this->object->setProperty('x', null);
        $instance = $this->object->getInstance($this->container);
        $this->assertAttributeEquals('U.S.S. Submergible', '_name', $instance);
    }

    /**
     * Tests the 'getInstance' method
     */
    public function testGetInstanceException()
    {
        $this->object->setProperty('error', 'error');
        $this->setExpectedException('Xyster_Container_Exception');
        $instance = $this->object->getInstance($this->container);
    }
    
    /**
     * Tests the 'setProperties' method
     */
    public function testSetProperties()
    {
        $map = new Xyster_Collection_Map_String;
        $map['abc'] = '123';
        $map['name'] = 'U.S.S. Submergible';
        
        $this->object->setProperties($map);
        $this->assertAttributeSame($map, '_properties', $this->object);
    }

    /**
     * Tests the 'setProperty' method
     */
    public function testSetProperty()
    {
        $map = new Xyster_Collection_Map_String;
        $map['name'] = 'U.S.S. Submergible';
        
        $this->object->setProperty('name', 'U.S.S. Submergible');
        $this->assertAttributeEquals($map, '_properties', $this->object);
    }

    /**
     * Tests the 'toString' method
     */
    public function test__toString()
    {
        $this->assertSame('PropertyApplied:' . $this->delegate->__toString(), $this->object->__toString());
    }
}

// Call Xyster_Container_Behavior_PropertyApplicatorTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Container_Behavior_PropertyApplicatorTest::main') {
    Xyster_Container_Behavior_PropertyApplicatorTest::main();
}
