<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Orm
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
// Call Xyster_Orm_Type_TimeTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Orm_Type_TimeTest::main');
}
require_once dirname(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'Xyster/Orm/Type/Time.php';
require_once 'Xyster/Db/Statement/Stub.php';

/**
 * Test class for Xyster_Orm_Type_Time.
 * Generated by PHPUnit on 2008-07-27 at 15:31:06.
 */
class Xyster_Orm_Type_TimeTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Xyster_Orm_Type_Time
     */
    protected $object;

    /**
     * Runs the test methods of this class.
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';
        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Orm_Type_TimeTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->object = new Xyster_Orm_Type_Time;
    }

    /**
     * Tests the 'get' method
     */
    public function testGet()
    {
        $stmt = new Xyster_Db_Statement_Stub;
        $stmt->columnValues['foo'] = '11:59:45';
        $date = new Zend_Date('11:59:45', Zend_Date::TIMES);
        $sess = $this->getMock('Xyster_Orm_Session_Interface');
        $this->assertEquals($date, $this->object->get($stmt, array('foo'), 0, $sess));
    }

    /**
     * Tests the 'getDataType' method
     */
    public function testGetDataType()
    {
        $this->assertSame(Xyster_Db_DataType::Time(), $this->object->getDataType());
    }

    /**
     * Tests the 'getName' method
     */
    public function testGetName()
    {
        $this->assertEquals('time', $this->object->getName());
    }

    /**
     * Tests the 'getReturnedType' method
     */
    public function testGetReturnedType()
    {
        $type = $this->object->getReturnedType();
        $this->assertType('Xyster_Type', $type);
        $this->assertEquals('Zend_Date', $type->getName());
        $this->assertSame($type, $this->object->getReturnedType());
    }

    /**
     * Tests the 'isEqual' method
     *
     */
    public function testIsEqual()
    {
        $a = date('H:i:s');
        $b = new Zend_Date($a, Zend_Date::TIMES);
        $this->assertTrue($this->object->isEqual($a, $b));
        $this->assertFalse($this->object->isEqual($a, '-1 day'));
    }
    
    /**
     * Tests the 'set' method
     */
    public function testSet()
    {
        $stmt = new Xyster_Db_Statement_Stub;
        $sess = $this->getMock('Xyster_Orm_Session_Interface');
        $date = new Zend_Date('11:59:45', Zend_Date::TIMES);
        $this->object->set($stmt, $date, 0, $sess, array(true));
        $this->assertEquals($date->get(Zend_Date::TIMES), $stmt->values[0]);
    }
}

// Call Xyster_Orm_Type_TimeTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Orm_Type_TimeTest::main') {
    Xyster_Orm_Type_TimeTest::main();
}
