<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Validate
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id: NotNullTest.php 189 2008-01-07 22:34:16Z doublecompile $
 */

// Call Xyster_Validate_NotNullTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Validate_NotNullTest::main');
}
require_once dirname(dirname(dirname(__FILE__))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'Xyster/Validate/NotNull.php';

/**
 * Test class for Xyster_Validate_NotNull.
 * Generated by PHPUnit on 2008-06-07 at 17:12:17.
 */
class Xyster_Validate_NotNullTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Xyster_Validate_NotNull
     */
    public $validator;
    
    /**
     * Runs the test methods of this class.
     *
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';
        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Validate_NotNullTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture
     * 
     */
    protected function setUp()
    {
        $this->validator = new Xyster_Validate_NotNull();
    }
    
    /**
     * Tests basic validation for a NotNull
     *
     */
    public function testBasic()
    {
        $valuesExpected = array(
            array(null, false),
            array('moo', true),
            array('', true),
            array(0, true),
            array(false, true)
            );
        foreach ($valuesExpected as $element) {
            $this->assertEquals($element[1], $this->validator->isValid($element[0]));
        }
    }
    
    /**
     * Ensures that getMessages() returns expected default value
     *
     * @return void
     */
    public function testGetMessages()
    {
        $this->assertEquals(array(), $this->validator->getMessages());
    }
    
}

// Call Xyster_Validate_NotNullTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Validate_NotNullTest::main') {
    Xyster_Validate_NotNullTest::main();
}
