<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Validate
 * @copyright Copyright LibreWorks, LLC (http://libreworks.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id: NotNullTest.php 189 2008-01-07 22:34:16Z doublecompile $
 */
namespace XysterTest\Validate;
use Xyster\Validate\NotNull;
/**
 * Test class for Xyster_Validate_NotNull.
 * Generated by PHPUnit on 2008-06-07 at 17:12:17.
 */
class NotNullTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var NotNull
     */
    public $validator;

    /**
     * Sets up the fixture
     * 
     */
    protected function setUp()
    {
        $this->validator = new NotNull();
    }
    
    /**
     * Tests basic validation for a NotNull
     *
     */
    public function testBasic()
    {
        $valuesExpected = array(
            array(null, false),
            array('moo', true),
            array('', true),
            array(0, true),
            array(false, true)
            );
        foreach ($valuesExpected as $element) {
            $this->assertEquals($element[1], $this->validator->isValid($element[0]));
        }
    }
    
    /**
     * Ensures that getMessages() returns expected default value
     *
     * @return void
     */
    public function testGetMessages()
    {
        $this->assertEquals(array(), $this->validator->getMessages());
    }    
}
