<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Container
 * @copyright Copyright (c) Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
require_once dirname(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'Xyster/Container/Provider/Caching.php';
require_once 'Xyster/Container/Injector/Standard.php';
require_once 'Xyster/Container.php';

/**
 * Test class for Xyster_Container_Provider_Caching.
 * Generated by PHPUnit on 2009-06-14 at 19:14:07.
 */
class Xyster_Container_Provider_CachingTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Xyster_Container_Provider_Caching
     */
    protected $object;

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->object = new Xyster_Container_Provider_Caching(
            new Xyster_Container_Injector_Standard(
                Xyster_Container::definition('Xyster_Collection', 'colly')));
    }

    public function testGet()
    {
        $object = $this->object->get(new Xyster_Container());
        $object2 = $this->object->get(new Xyster_Container());
        self::assertSame($object2, $object);
    }

    public function testGetLabel()
    {
        self::assertEquals('Caching', $this->object->getLabel());
    }
}
