<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Container
 * @copyright Copyright LibreWorks, LLC (http://libreworks.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
namespace XysterTest\Container\Provider;
use Xyster\Container\Provider\Delegate;
use Xyster\Container\Container;
/**
 * Test class for Xyster_Container_Provider_Delegate.
 * Generated by PHPUnit on 2009-06-14 at 19:17:26.
 */
class DelegateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var    Delegate
     */
    protected $object;

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->object = new DelegateTest_Impl(
            new \Xyster\Container\Injector\Standard(
                Container::definition('\Xyster\Collection\Collection', 'colly')));
    }

    public function testGetName()
    {
        self::assertEquals('colly', $this->object->getName());
    }

    public function testGetType()
    {
        self::assertEquals(new \Xyster\Type\Type('\Xyster\Collection\Collection'), $this->object->getType());
    }

    public function testValidate()
    {
        $this->object->validate(new Container);
    }

    public function test__toString()
    {
        self::assertEquals('Impl:Injector:colly', $this->object->__toString());
    }
}

class DelegateTest_Impl extends Delegate
{
    public function get(\Xyster\Container\IContainer $container, \Xyster\Type\Type $into = null)
    {
        return null;
    }
    
    public function getLabel()
    {
        return 'Impl';
    }
}
