<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Type
 * @copyright Copyright LibreWorks, LLC (http://libreworks.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
namespace XysterTest\Type\Property;
use Xyster\Type\Property\Map;
/**
 * Test class for Xyster_Type_Property_Map.
 * Generated by PHPUnit on 2008-07-27 at 13:52:58.
 */
class MapTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var    \Xyster\Type\Property\Map
     */
    protected $object;

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->object = new Map('foobar');
    }

    /**
     * Tests the 'get' and 'set' methods
     */
    public function testGetAndSetArray()
    {
        $example = array('foobar' => null);
        $this->object->set(&$example, 'Hello, world!');
        $this->assertEquals('Hello, world!', $this->object->get($example));
    }

    /**
     * Tests the 'get' and 'set' methods
     */
    public function testGetAndSetArrayAccess()
    {
        $example = new \ArrayObject;
        $this->object->set($example, 'Hello, world!');
        $this->assertEquals('Hello, world!', $this->object->get($example));
    }
}
