<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Type
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
// Call Xyster_Type_Property_MethodTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Type_Property_MethodTest::main');
}
require_once dirname(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'Xyster/Type/Property/Method.php';

/**
 * Test class for Xyster_Type_Property_Method.
 * Generated by PHPUnit on 2008-07-27 at 13:37:43.
 */
class Xyster_Type_Property_MethodTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Xyster_Type_Property_Method
     */
    protected $object;

    /**
     * Runs the test methods of this class.
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';
        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Type_Property_MethodTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->object = new Xyster_Type_Property_Method('foobar');
    }

    /**
     * Tests the 'get' and 'set' methods
     */
    public function testGetAndSet()
    {
        $example = new Xyster_Type_Property_MethodTest_Example;
        $this->object->set($example, 'Hello, world!');
        $this->assertEquals('Hello, world!', $this->object->get($example));
    }
}

class Xyster_Type_Property_MethodTest_Example
{
    protected $_foobar;
    
    public function getFoobar()
    {
        return $this->_foobar;
    }
    
    public function setFoobar( $value )
    {
        $this->_foobar = $value;
    }
}

// Call Xyster_Type_Property_MethodTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Type_Property_MethodTest::main') {
    Xyster_Type_Property_MethodTest::main();
}
