<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Type
 * @copyright Copyright LibreWorks, LLC (http://libreworks.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
namespace XysterTest\Type\Property;
use Xyster\Type\Property\Method;
/**
 * Test class for Xyster_Type_Property_Method.
 * Generated by PHPUnit on 2008-07-27 at 13:37:43.
 */
class MethodTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var    \Xyster\Type\Property\Method
     */
    protected $object;

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->object = new Method('foobar');
    }

    /**
     * Tests the 'get' and 'set' methods
     */
    public function testGetAndSet()
    {
        $example = new MethodTest_Example;
        $this->object->set($example, 'Hello, world!');
        $this->assertEquals('Hello, world!', $this->object->get($example));
    }
}

class MethodTest_Example
{
    protected $_foobar;
    
    public function getFoobar()
    {
        return $this->_foobar;
    }
    
    public function setFoobar( $value )
    {
        $this->_foobar = $value;
    }
}
