<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Container
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */

// Call Xyster_Container_Parameter_ConstantTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Container_Parameter_ConstantTest::main');
}

/**
 * Test helper
 */
require_once dirname(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR . 'TestHelper.php';

require_once 'PHPUnit/Framework.php';
require_once 'Xyster/Container/Parameter/Constant.php';

/**
 * Test class for Xyster_Container_Parameter_Constant.
 * Generated by PHPUnit on 2007-12-11 at 17:28:32.
 */
class Xyster_Container_Parameter_ConstantTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Xyster_Container_Parameter_Constant
     */
    protected $object;

    /**
     * Runs the test methods of this class.
     * 
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite(__CLASS__);
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture. This method is called before a test is executed.
     *
     */
    protected function setUp()
    {
        $this->object = new Xyster_Container_Parameter_Constant('unittest');
    }

    /**
     * Tests the 'accept' method
     */
    public function testAccept()
    {
        require_once 'Xyster/Container/Visitor/Mock.php';
        $visitor = new Xyster_Container_Visitor_Mock;
        $this->object->accept($visitor);
        $this->assertEquals(1, $visitor->getCalled('visitParameter'));
    }

    /**
     * Tests the 'isResolvable' method
     */
    public function testIsResolvable()
    {
        require_once 'Xyster/Container.php';
        $container = new Xyster_Container;
        $key = new Xyster_Type('Xyster_Type');
        $container->addComponent($key);
        $adapter = $container->getComponentAdapter($key);
        $parameters = $key->getClass()->getConstructor()->getParameters();
        $parameter = $parameters[0];
        $this->assertTrue($this->object->isResolvable($container, $adapter, $parameter));
    }

    /**
     * Tests the 'resolveInstance' method
     */
    public function testResolveInstance()
    {
        require_once 'Xyster/Container.php';
        $container = new Xyster_Container;
        $key = new Xyster_Type('Xyster_Type');
        $container->addComponent($key);
        $adapter = $container->getComponentAdapter($key);
        $parameters = $key->getClass()->getConstructor()->getParameters();
        $parameter = $parameters[0];
        $this->assertSame('unittest', $this->object->resolveInstance($container, $adapter, $parameter));
    }

    /**
     * Tests the 'verify' method
     * 
     * As long as no exception is thrown, the test passes
     */
    public function testVerify()
    {
        require_once 'Xyster/Container.php';
        $container = new Xyster_Container;
        $key = new Xyster_Type('Xyster_Type');
        $container->addComponent($key);
        $adapter = $container->getComponentAdapter($key);
        $parameters = $key->getClass()->getConstructor()->getParameters();
        $parameter = $parameters[0];
        $this->object->verify($container, $adapter, $parameter);
    }
    
    /**
     * Tests the 'verify' method to fail
     *
     */
    public function testVerifyFail()
    {
        require_once 'Xyster/Container.php';
        $container = new Xyster_Container;
        require_once 'Xyster/Collection/Map.php';
        $key = new Xyster_Type('Xyster_Collection_Map');
        $container->addComponent($key);
        $adapter = $container->getComponentAdapter($key);
        $parameters = $key->getClass()->getConstructor()->getParameters();
        $parameter = $parameters[0];
        $this->setExpectedException('Xyster_Container_Exception');
        $this->object->verify($container, $adapter, $parameter);
    }
}

// Call Xyster_Container_Parameter_ConstantTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Container_Parameter_ConstantTest::main') {
    Xyster_Container_Parameter_ConstantTest::main();
}
