<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Filter
 * @copyright Copyright LibreWorks, LLC (http://libreworks.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
namespace XysterTest\Filter;
use Xyster\Filter\TitleCase;
/**
 * Test class for Xyster_Filter_TitleCase.
 * Generated by PHPUnit on 2007-09-11 at 19:28:58.
 */
class TitleCaseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TitleCase
     */
    public $filter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     */
    protected function setUp()
    {
        $this->filter = new TitleCase;
    }
    
    /**
     * Tests basic operation of filter class
     *
     */
    public function testBasic()
    {
        $valuesExpected = array(
            'The great escape of our hero from coding hades' =>
                'The Great Escape of Our Hero from Coding Hades',
            
            'I WANT THIS STRING TO BE IN TITLE CASE' => 
                'I Want This String to Be in Title Case',
        
            'HOW ÄBÖUT INTERNATIONAL LETTERS' =>
                'How ÄbÖut International Letters' // we'll leave this alone for now
        );

        foreach ($valuesExpected as $input => $output) {
            $this->assertEquals($output, $this->filter->filter($input));
        }
    }    
}
