<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Container
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
require_once dirname(dirname(dirname(__FILE__))) . DIRECTORY_SEPARATOR . 'Injection/Factory/CommonTest.php';
require_once 'PHPUnit/Framework.php';
require_once 'Xyster/Container/Injection/Factory/Constructor.php';
require_once 'Xyster/Container/Adapter/Instance.php';

/**
 * Test class for Xyster_Container_Injection_Factory_Adaptive.
 * Generated by PHPUnit on 2007-12-31 at 09:30:26.
 */
abstract class Xyster_Container_Behavior_Factory_CommonTest extends Xyster_Container_Injection_Factory_CommonTest
{
    /**
     * @var Xyster_Container_Behavior_Factory
     */
    protected $object;
    
    /**
     * Tests the 'addComponentAdapter' method
     */
    public function testAddComponentAdapter()
    {
        $key = new Xyster_Type('ArrayObject');
        $instance = new ArrayObject;
        $adapter = new Xyster_Container_Adapter_Instance($key, $instance, $this->monitor);
        $return = $this->object->addComponentAdapter($this->monitor, $this->properties, $adapter);
        $this->assertType($this->_getInjectorClass(), $return);
        $this->assertEquals($return->getImplementation(), $key);
    }

    /**
     * Tests the 'wrap' method
     */
    public function testWrap()
    {
        $delegate = new Xyster_Container_Injection_Factory_Constructor;
        $return = $this->object->wrap($delegate);
        $this->assertSame($this->object, $return);
        $this->assertAttributeSame($delegate, '_delegate', $this->object);
    }
    
    protected function _getInjectorClass()
    {
        return 'Xyster_Container_Adapter';
    }
}