<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Data
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
// Call Xyster_Data_Field_Mapper_MapTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Data_Field_Mapper_MapTest::main');
}
require_once dirname(dirname(dirname(dirname(dirname(__FILE__))))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'Xyster/Data/Field/Mapper/Map.php';

/**
 * Test class for Xyster_Data_Field_Mapper_Map.
 * Generated by PHPUnit on 2008-07-27 at 13:52:58.
 */
class Xyster_Data_Field_Mapper_MapTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Xyster_Data_Field_Mapper_Map
     */
    protected $object;

    /**
     * Runs the test methods of this class.
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';
        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Data_Field_Mapper_MapTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->object = new Xyster_Data_Field_Mapper_Map('foobar');
    }

    /**
     * Tests the 'get' and 'set' methods
     */
    public function testGetAndSetArray()
    {
        $example = array('foobar' => null);
        $this->object->set(&$example, 'Hello, world!');
        $this->assertEquals('Hello, world!', $this->object->get($example));
    }

    /**
     * Tests the 'get' and 'set' methods
     */
    public function testGetAndSetArrayAccess()
    {
        $example = new ArrayObject;
        $this->object->set($example, 'Hello, world!');
        $this->assertEquals('Hello, world!', $this->object->get($example));
    }
}

// Call Xyster_Data_Field_Mapper_MapTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Data_Field_Mapper_MapTest::main') {
    Xyster_Data_Field_Mapper_MapTest::main();
}
