<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Container
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */

// Call Xyster_Container_Injection_SetterTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Container_Injection_SetterTest::main');
}

require_once dirname(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR . 'TestHelper.php';

require_once 'PHPUnit/Framework.php';
require_once 'Xyster/Container/Injection/Setter.php';
require_once dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR . '_files/Sdi.php';
require_once 'Xyster/Type.php';
require_once 'Xyster/Container.php';

/**
 * Test class for Xyster_Container_Injection_Setter.
 * Generated by PHPUnit on 2007-12-31 at 08:59:44.
 */
class Xyster_Container_Injection_SetterTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Xyster_Container_Injection_Setter
     */
    protected $object;

    /**
     * @var Xyster_Container
     */
    protected $container;
    
    /**
     * Runs the test methods of this class.
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Container_Injection_SetterTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $key = new Xyster_Type('RocketShip');
        $this->object = new Xyster_Container_Injection_Setter($key, $key);
        $this->container = new Xyster_Container;
        $this->container->addComponent('RocketPilot')
            ->addComponent('RocketFuel')
            ->addComponent('SpaceSuit');
            
    }
    
    /**
     * Tests the 'accept' method
     */
    public function testAccept()
    {
        require_once 'Xyster/Container/Visitor/Mock.php';
        $visitor = new Xyster_Container_Visitor_Mock;
        $this->object->accept($visitor);
        $this->assertEquals(1, $visitor->getCalled('visitComponentAdapter'));
    }
    
    /**
     * Tests the 'getInstance' method
     */
    public function testGetInstance()
    {
        $inst = $this->object->getInstance($this->container);
        $this->assertType('RocketShip', $inst);
        $this->assertType('Astronaut', $inst->getPilot());
    }

    /**
     * Tests the 'verify' method
     */
    public function testVerify()
    {
        $this->object->verify($this->container);
    }
    
    public function testVerifyNotLoaded()
    {
        $this->container = new Xyster_Container;
        $this->setExpectedException('Xyster_Container_Exception');
        $this->object->verify($this->container);
    }

    /**
     * Tests the 'toString' method
     */
    public function test__toString()
    {
        $this->assertSame('SetterInjector-Class RocketShip', $this->object->__toString());
    }
    
    /**
     * Tests a bad method invocation
     *
     */
    public function testBadSet()
    {
        $key = new Xyster_Type('ExtraTerrestrial');
        $container = new Xyster_Container;
        $container->addConfig('color', 'blue');
        $inj = new Xyster_Container_Injection_Setter($key, $key);
        $this->setExpectedException('Xyster_Container_Exception');
        $inj->getInstance($container);
    }
}

// Call Xyster_Container_Injection_SetterTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Container_Injection_SetterTest::main') {
    Xyster_Container_Injection_SetterTest::main();
}
