<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Collection
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */

// Call Xyster_Collection_List_EmptyTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Collection_List_EmptyTest::main');
}

require_once dirname(dirname(dirname(__FILE__))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'PHPUnit/Framework.php';
require_once 'Xyster/Collection/List/Empty.php';

/**
 * Test class for Xyster_Collection_List_Empty.
 * Generated by PHPUnit on 2008-01-31 at 16:15:02.
 */
class Xyster_Collection_List_EmptyTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Xyster_Collection_List_Empty
     */
    protected $object;

    /**
     * Runs the test methods of this class.
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Collection_List_EmptyTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->object = new Xyster_Collection_List_Empty;
    }

    /**
     * Tests the 'add' method
     */
    public function testAdd()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
        $this->object->add(null);
    }

    /**
     * Tests the 'clear' method
     */
    public function testClear()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
        $this->object->clear();
    }

    /**
     * Tests the 'contains' method
     */
    public function testContains()
    {
       $this->assertFalse($this->object->contains(null));
    }

    /**
     * Tests the 'containsAll' method
     */
    public function testContainsAll()
    {
    	$this->assertFalse($this->object->containsAll($this->object));
    }

    /**
     * Tests the 'containsAny' method
     */
    public function testContainsAny()
    {
        $this->assertFalse($this->object->containsAny($this->object));
    }

    /**
     * Tests the 'count' method
     */
    public function testCount()
    {
        $this->assertSame(0, $this->object->count());
    }

    /**
     * Tests the 'get' method
     */
    public function testGet()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
    	$this->object->get(0);
    }

    /**
     * Tests the 'getIterator' method
     */
    public function testGetIterator()
    {
        $this->assertType('EmptyIterator', $this->object->getIterator());
    }

    /**
     * Tests the 'indexOf' method
     */
    public function testIndexOf()
    {
        $this->assertNull($this->object->indexOf(null));
    }

    /**
     * Tests the 'insert' method
     */
    public function testInsert()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
    	$this->object->insert(0, null);
    }

    /**
     * Tests the 'insertAll' method
     */
    public function testInsertAll()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
    	$this->object->insertAll(0, $this->object);
    }

    /**
     * Tests the 'isEmpty' method
     */
    public function testIsEmpty()
    {
        $this->assertTrue($this->object->isEmpty());
    }

    /**
     * Tests the 'merge' method
     */
    public function testMerge()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
    	$this->object->merge($this->object);
    }

    /**
     * Tests the 'offsetExists' method
     */
    public function testOffsetExists()
    {
        $this->assertFalse($this->object->offsetExists(0));
    }

    /**
     * Tests the 'offsetGet' method
     */
    public function testOffsetGet()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
    	$this->object->offsetGet(0);
    }

    /**
     * Tests the 'offsetSet' method
     */
    public function testOffsetSet()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
    	$this->object->offsetSet(0, null);
    }

    /**
     * Tests the 'offsetUnset' method
     */
    public function testOffsetUnset()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
    	$this->object->offsetUnset(0);
    }

    /**
     * Tests the 'remove' method
     */
    public function testRemove()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
    	$this->object->remove(null);
    }

    /**
     * Tests the 'removeAll' method
     */
    public function testRemoveAll()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
    	$this->object->removeAll($this->object);
    }

    /**
     * Tests the 'removeAt' method
     */
    public function testRemoveAt()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
        $this->object->removeAt(0);
    }

    /**
     * Tests the 'retainAll' method
     */
    public function testRetainAll()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
        $this->object->retainAll($this->object);
    }

    /**
     * Tests the 'set' method
     */
    public function testSet()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
        $this->object->set(0, null);
    }

    /**
     * Tests the 'slice' method
     */
    public function testSlice()
    {
        $this->setExpectedException('Xyster_Collection_Exception');
        $this->object->slice(0, 1);
    }

    /**
     * Tests the 'toArray' method
     */
    public function testToArray()
    {
        $this->assertSame(array(), $this->object->toArray());
    }
}

// Call Xyster_Collection_List_EmptyTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Collection_List_EmptyTest::main') {
    Xyster_Collection_List_EmptyTest::main();
}
