<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Container
 * @copyright Copyright (c) Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
require_once dirname(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'Xyster/Container/Injector/Standard.php';
require_once 'Xyster/Container/Definition.php';
require_once 'Xyster/Container.php';
require_once 'Xyster/Container/_files/Cdi.php';

/**
 * Test class for Xyster_Container_Injector_Standard.
 * Generated by PHPUnit on 2009-06-10 at 19:16:21.
 */
class Xyster_Container_Injector_StandardTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Xyster_Container_Injector_Standard
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $def = new Xyster_Container_Definition('Submarine');
        $def->constructorArg('SubmarineCaptain')
            ->constructorArg('SubFuel')
            ->constructorArg(array('Sailor1', 'Sailor2'))
            ->property('location', 'Somewhere')
            ->property('name', 'USS Enterprise');
        $this->object = new Xyster_Container_Injector_Standard($def);
    }

    public function testGet()
    {
        $def = new Xyster_Container_Definition('SubmarineCaptain');
        $def->constructorArg('ScubaGear');
        $def->initMethod('navigate');
        $container = new Xyster_Container();
        $container->add($def)
            ->add(new Xyster_Container_Definition('SubFuel'))
            ->add(new Xyster_Container_Definition('ScubaGear'));
        $object = $this->object->get($container);
        self::assertType('Submarine', $object);
        self::assertAttributeEquals(new SubFuel(), '_fuel', $object);
        self::assertType('SubmarineCaptain', $object->getCaptain());
        self::assertAttributeEquals('USS Enterprise', '_name', $object);
        self::assertAttributeEquals('Somewhere', '_location', $object);
        self::assertAttributeEquals($container, '_container', $object->getCaptain());
        self::assertAttributeEquals(true, '_navigated', $object->getCaptain());
        $object2 = $this->object->get($container);
        self::assertNotSame($object2, $object);
        self::assertEquals($object2, $object);
    }
    
    public function testGetBad()
    {
        $this->setExpectedException('Xyster_Container_Injector_Exception', 'Cannot inject method argument capn into Submarine: key not found in the container: SubmarineCaptain');
        $this->object->get(new Xyster_Container());
    }
    
    public function testGetBad2()
    {
        $this->setExpectedException('Xyster_Container_Injector_Exception', 'The number of required method parameters must equal the number of arguments provided');
        $def = new Xyster_Container_Definition('Submarine');
        $def->constructorArg('SubmarineCaptain');
        $object = new Xyster_Container_Injector_Standard($def);
        $object->get(new Xyster_Container());
    }
    
    public function testGetName()
    {
        self::assertEquals('Submarine', $this->object->getName());
    }
    
    public function testGetType()
    {
        self::assertEquals(new Xyster_Type('Submarine'), $this->object->getType());
    }

    public function testGetLabel()
    {
        self::assertEquals('Injector', $this->object->getLabel());
    }

    public function testConstructAbstract()
    {
        $this->setExpectedException('Xyster_Container_Injector_Exception',
        	'Xyster_Container_Injector_AbstractInjector is not a concrete class');
        new Xyster_Container_Injector_Standard(new Xyster_Container_Definition('Xyster_Container_Injector_AbstractInjector'));
    }
    
    public function testToString()
    {
        self::assertEquals('Injector:Submarine', $this->object->__toString());
    }
    
    public function testValidateError1()
    {
        $this->setExpectedException('Xyster_Container_Injector_Exception');
        $this->object->validate(new Xyster_Container());
    }
    
    public function testValidate()
    {
        $def = new Xyster_Container_Definition('SubmarineCaptain');
        $def->constructorArg('ScubaGear');
        $container = new Xyster_Container();
        $container->add($def)
            ->add(new Xyster_Container_Definition('SubFuel'))
            ->add(new Xyster_Container_Definition('ScubaGear'));
        $this->object->validate($container);
    }
}
