<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Orm
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
// Call Xyster_Orm_Runtime_Property_StandardTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Orm_Runtime_Property_StandardTest::main');
}
require_once dirname(dirname(dirname(dirname(dirname(__FILE__))))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'Xyster/Orm/Runtime/Property/Standard.php';

/**
 * Test class for Xyster_Orm_Runtime_Property_Standard.
 * Generated by PHPUnit on 2008-08-02 at 11:28:52.
 */
class Xyster_Orm_Runtime_Property_StandardTest extends PHPUnit_Framework_TestCase
{
    /**
     * Runs the test methods of this class.
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';
        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Orm_Runtime_Property_StandardTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Tests the basic operation of the class
     */
    public function testBasic()
    {
        require_once 'Xyster/Orm/Type/String.php';
        $type = new Xyster_Orm_Type_String;
        $prop = new Xyster_Orm_Runtime_Property_Standard('foobar', $type, true, true, true, true, true);
        $this->assertEquals('foobar', $prop->getName());
        $this->assertSame($type, $prop->getType());
        $this->assertTrue($prop->isLazy());
        $this->assertTrue($prop->isInsertGenerated());
        $this->assertTrue($prop->isUpdateGenerated());
        $this->assertTrue($prop->isNullable());
        $this->assertTrue($prop->isVersionable());
        $this->assertEquals('Property(foobar:string)', $prop->__toString());
        
        $prop = new Xyster_Orm_Runtime_Property_Standard('foobar', $type, false, false, true, true, false);
        $this->assertFalse($prop->isLazy());
        $this->assertFalse($prop->isInsertGenerated());
        $this->assertTrue($prop->isUpdateGenerated());
        $this->assertTrue($prop->isNullable());
        $this->assertFalse($prop->isVersionable());
    }
}

// Call Xyster_Orm_Runtime_Property_StandardTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Orm_Runtime_Property_StandardTest::main') {
    Xyster_Orm_Runtime_Property_StandardTest::main();
}
