<?php
/**
 * Xyster Framework
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category  Xyster
 * @package   UnitTests
 * @subpackage Xyster_Db
 * @copyright Copyright (c) 2007-2008 Irrational Logic (http://irrationallogic.net)
 * @license   http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version   $Id$
 */
// Call Xyster_Db_Gateway_TableBuilder_PrimaryKeyTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Xyster_Db_Gateway_TableBuilder_PrimaryKeyTest::main');
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";
require_once dirname(dirname(dirname(dirname(dirname(__FILE__))))) . DIRECTORY_SEPARATOR . 'TestHelper.php';
require_once 'Xyster/Db/Gateway/TableBuilder/PrimaryKey.php';

/**
 * Test class for Xyster_Db_Gateway_TableBuilder_PrimaryKey.
 * Generated by PHPUnit on 2008-03-18 at 13:00:34.
 */
class Xyster_Db_Gateway_TableBuilder_PrimaryKeyTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Xyster_Db_Gateway_TableBuilder_PrimaryKey
     */
    protected $object;

    protected $columns = array('column1', 'column2', 'column3');
    
    /**
     * Runs the test methods of this class.
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Xyster_Db_Gateway_TableBuilder_PrimaryKeyTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
    	$this->object = new Xyster_Db_Gateway_TableBuilder_PrimaryKey($this->columns);
    }
    
    /**
     * Tests the 'getColumns' method
     */
    public function testGetColumns()
    {
        $this->assertEquals($this->columns, $this->object->getColumns());
    }
}

// Call Xyster_Db_Gateway_TableBuilder_PrimaryKeyTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Xyster_Db_Gateway_TableBuilder_PrimaryKeyTest::main') {
    Xyster_Db_Gateway_TableBuilder_PrimaryKeyTest::main();
}
